services:
  unoserver:
    image: libreofficedocker/libreoffice-unoserver:3.19-9c28c22
    ports:
      - "2004:2004"    # REST API

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    env_file:
      - .env              # AWS creds
    depends_on:
      - unoserver
    environment:
      # point the converter at the unoserver container:
      UNOSERVER_ADDR: "unoserver:2004"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local        # NEXT_PUBLIC_API_URL, any other FRONTEND_ vars
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: "http://localhost:5001"
