services:
  unoserver:
    image: libreofficedocker/libreoffice-unoserver:3.19-9c28c22
    ports:
      - "2004:2004"    # REST API
      - "2002:2002"    # unoconv socket if needed

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - unoserver
    environment:
      # point the converter at the unoserver container:
      UNOSERVER_ADDR: "unoserver:2004"
      # (and your AWS env vars or add an env_file)
